version: "3"

services:
  app:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codepix
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db

volumes:
  dbdata: